name: city_airport
version: 0.0.1
description: An airport, with field, a hangar, and cargo handling
autor: Carlos Villanueva
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
dev_dependencies:
  test: '0.12.3'